config/routes.rb
Rails.application.routes.draw do
  resources :guilds
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guild.rb
class Guild < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guilds_controller.rb
class GuildsController < ApplicationController
  before_action :set_guild, only: [:show, :edit, :update, :destroy]

  # GET /guilds
  # GET /guilds.json
  def index
    @guilds = Guild.all
  end

  # GET /guilds/1
  # GET /guilds/1.json
  def show
  end

  # GET /guilds/new
  def new
    @guild = Guild.new
  end

  # GET /guilds/1/edit
  def edit
  end

  # POST /guilds
  # POST /guilds.json
  def create
    @guild = Guild.new(guild_params)

    respond_to do |format|
      if @guild.save
        format.html { redirect_to @guild, notice: 'Guild was successfully created.' }
        format.json { render :show, status: :created, location: @guild }
      else
        format.html { render :new }
        format.json { render json: @guild.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guilds/1
  # PATCH/PUT /guilds/1.json
  def update
    respond_to do |format|
      if @guild.update(guild_params)
        format.html { redirect_to @guild, notice: 'Guild was successfully updated.' }
        format.json { render :show, status: :ok, location: @guild }
      else
        format.html { render :edit }
        format.json { render json: @guild.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guilds/1
  # DELETE /guilds/1.json
  def destroy
    @guild.destroy
    respond_to do |format|
      format.html { redirect_to guilds_url, notice: 'Guild was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guild
      @guild = Guild.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guild_params
      params.require(:guild).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guilds_helper.rb
module GuildsHelper
end

app/views/guilds/_form.html.erb
<%= form_with(model: guild, local: true) do |form| %>
  <% if guild.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guild.errors.count, "error") %> prohibited this guild from being saved:</h2>

      <ul>
        <% guild.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/guilds/edit.html.erb
<h1>Editing Guild</h1>

<%= render 'form', guild: @guild %>

<%= link_to 'Show', @guild %> |
<%= link_to 'Back', guilds_path %>

app/views/guilds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guilds</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guilds.each do |guild| %>
      <tr>
        <td><%= guild.title %></td>
        <td><%= link_to 'Show', guild %></td>
        <td><%= link_to 'Edit', edit_guild_path(guild) %></td>
        <td><%= link_to 'Destroy', guild, method: :delete, data: { confirm: 'Are you sure want to delete?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guild', new_guild_path %>

app/views/guilds/new.html.erb
<h1>New Guild</h1>

<%= render 'form', guild: @guild %>

<%= link_to 'Back', guilds_path %>

app/views/guilds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @guild.title %>
</p>

<%= link_to 'Edit', edit_guild_path(@guild) %> |
<%= link_to 'Back', guilds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HellowWorld</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>